---
- name: Install lizardfs client
  package:
    name: lizardfs-client
    state: present

- name: Mount LizardFS volumes
  mount:
    path: "{{ item.path }}"
    src: mfsmount
    opts: "{{ item.opts | default('mfsmaster=lizardfs_masterserver_host') }}"
    fstype: fuse
    state: "{{ item.state | default('mounted') }}"
  loop: "{{ lizardfs_mounts }}"
  when: lizardfs_mounts is defined and lizardfs_mounts|length > 0
