---
- name: Install LizardFS masterserver
  package:
    name: lizardfs-master
    state: present

- name: Install LizardFS masterserver configs
  template:
    src: "{{ item }}.j2"
    dest: /etc/mfs/{{ item }}
    owner: root
    group: root
    mode: 0644
  loop:
    - mfsexports.cfg
    - mfsgoals.cfg
    - mfsmaster.cfg
    - mfstopology.cfg
  notify: reload lizardfs-masterserver

- name: Create empty metadata file for LizardFS masterserver
  copy:
    src: /var/lib/mfs/metadata.mfs.empty
    dest: /var/lib/mfs/metadata.mfs
    remote_src: true
    backup: yes
    mode: 0644
    force: no

- meta: flush_handlers
